name: Terraform Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        working-directory: terraform
        run: |
          terraform init \
            -backend-config="bucket=${{secrets.TF_BACKEND_BUCKET}}" \
            -backend-config="key=${{env.ENVIRONMENT}}/terraform.tfstate" \
            -backend-config="region=us-east-1"

      - name: Validate Terraform
        working-directory: terraform
        run: |
          terraform validate
          terraform fmt --check -recursive    

      - name: Plan Terraform
        working-directory: terraform
        run: terraform plan -out=tfplan


      